import 'package:flutter/material.dart';
import 'vitamin.dart';

final List<Vitamin> vitaminPresets = [
  Vitamin(
    id: null,
    name: 'Магний',
    abbreviation: 'Mg',
    dosage: 400.0,
    startDate: DateTime.now(),
    endDate: DateTime.now().add(const Duration(days: 30)),
    unit: 'мг',
    color: 0xFF9C27B0, // фиолетовый
    period: 'вечер',
    mealRelation: 'перед сном',
    compatibleWith: ['B6', 'D'],
    incompatibleWith: ['Кальций', 'Железо'],
    description: 'Минерал, участвующий в более чем 300 биохимических реакциях организма.',
    benefits: 'Поддерживает работу нервной системы, мышц, регулирует уровень сахара в крови.',
    organs: 'Нервная система, мышцы, сердце',
    dailyNorm: '400-420 мг для взрослых',
    bestTimeToTake: 'Вечером перед сном',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Витамин D',
    abbreviation: 'D',
    dosage: 2000.0,
    startDate: DateTime.now(),
    endDate: DateTime.now().add(const Duration(days: 30)),
    unit: 'МЕ',
    color: 0xFF2196F3, // синий
    period: 'утро',
    mealRelation: 'во время еды',
    compatibleWith: ['A', 'C', 'E', 'K2'],
    incompatibleWith: ['E'],
    description: 'Жирорастворимый витамин, который организм может синтезировать под воздействием солнечного света.',
    benefits: 'Укрепляет кости, поддерживает иммунигет, регулирует уровень кальция.',
    organs: 'Кости, иммунная система, кожа',
    dailyNorm: '600-800 МЕ для взрослых',
    bestTimeToTake: 'Утром во время завтрака',
    form: 'Капсулы',
  ),
  Vitamin(
    id: null,
    name: 'Витамин C',
    abbreviation: 'C',
    dosage: 1000.0,
    startDate: DateTime.now(),
    endDate: DateTime.now().add(const Duration(days: 30)),
    unit: 'мг',
    color: 0xFF4CAF50, // зеленый
    period: 'утро',
    mealRelation: 'после еды',
    compatibleWith: ['B1','B2','B3','B5','B6','B9','B12','E'],
    incompatibleWith: ['B1','B12'],
    description: 'Аскорбиновая кислота - водорастворимый витамин, мощный антиоксидант.',
    benefits: 'Укрепляет иммунитет, участвует в синтезе коллагена, улучшает усвоение железа.',
    organs: 'Иммунная система, кожа, кости, зубы',
    dailyNorm: '90 мг для взрослых',
    bestTimeToTake: 'Утром после завтрака',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Кальций',
    abbreviation: 'Ca',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFF1565C0, // тёмно-синий для Кальция
    period: 'вечер',
    mealRelation: 'во время еды',
    compatibleWith: ['D', 'K2'],
    incompatibleWith: ['Железо', 'Цинк', 'Магний', 'Тетрациклин', 'Фосфаты'],
    description: 'Минерал, необходимый для здоровья костей и зубов, а также для работы мышц и нервов.',
    benefits: 'Укрепляет кости и зубы, участвует в свертывании крови, работе мышц и нервов.',
    organs: 'Кости, зубы, мышцы, нервная система',
    dailyNorm: '1000-1300 мг для взрослых',
    bestTimeToTake: 'Вечером во время еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Витамин B12',
    abbreviation: 'B12',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFFC2185B, // тёмно-розовый для B12
    period: 'утро',
    mealRelation: 'во время еды',
    compatibleWith: ['B6', 'B9', 'Кальций'],
    incompatibleWith: ['Витамин C', 'Железо', 'Медь'],
    description: 'Водорастворимый витамин, играющий ключевую роль в работе нервной системы и образовании крови.',
    benefits: 'Поддерживает здоровье нервной системы, участвует в образовании красных кровяных телец, снижает утомляемость.',
    organs: 'Нервная система, кровь',
    dailyNorm: '2.4 мкг для взрослых',
    bestTimeToTake: 'Утром во время еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Омега-3',
    abbreviation: 'Ω',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFF42A5F5, // синий
    period: 'утро',
    mealRelation: 'во время еды',
    compatibleWith: ['Витамин E'],
    incompatibleWith: [],
    description: 'Полиненасыщенные жирные кислоты, важные для здоровья сердца и мозга.',
    benefits: 'Поддерживает здоровье сердца, мозга, суставов, улучшает состояние кожи.',
    organs: 'Сердце, мозг, суставы, кожа',
    dailyNorm: '250-500 мг EPA и DHA для взрослых',
    bestTimeToTake: 'Утром или днем во время еды',
    form: 'Капсулы',
  ),
  Vitamin(
    id: null,
    name: 'Цинк',
    abbreviation: 'Zn',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFF424242, // тёмно-серый для Цинка
    period: 'утро',
    mealRelation: 'после еды',
    compatibleWith: ['Витамин C', 'Витамин B6', 'Магний'],
    incompatibleWith: ['Кальций', 'Железо', 'Медь', 'Фолиевая кислота'],
    description: 'Минерал, участвующий в множестве ферментативных реакций, важен для иммунитета и обмена веществ.',
    benefits: 'Поддерживает иммунную систему, заживление ран, обоняние и вкус, здоровье кожи и волос.',
    organs: 'Иммунная система, кожа, волосы, органы чувств',
    dailyNorm: '11 мг для мужчин, 8 мг для женщин',
    bestTimeToTake: 'Утром или днем после еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Железо',
    abbreviation: 'Fe',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFFE57373, // красный
    period: 'утро',
    mealRelation: 'до еды',
    compatibleWith: ['Витамин C', 'Витамин B12', 'Фолиевая кислота'],
    incompatibleWith: ['Кальций', 'Магний', 'Цинк', 'Витамин E', 'Танины (чай, кофе)'],
    description: 'Минерал, ключевой компонент гемоглобина, необходим для транспортировки кислорода.',
    benefits: 'Предотвращает анемию, поддерживает энергию, необходим для роста и развития.',
    organs: 'Кровь, мышцы',
    dailyNorm: '8-18 мг для взрослых (зависит от пола и возраста)',
    bestTimeToTake: 'Утром натощак',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Витамин E',
    abbreviation: 'E',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFFBA68C8, // фиолетовый
    period: 'утро',
    mealRelation: 'во время еды',
    compatibleWith: ['Витамин C', 'Селен', 'Омега-3'],
    incompatibleWith: ['Железо', 'Витамин D', 'Витамин K'],
    description: 'Жирорастворимый антиоксидант, защищает клетки от повреждений.',
    benefits: 'Мощный антиоксидант, поддерживает здоровье кожи и волос, иммунную функцию.',
    organs: 'Кожа, волосы, иммунная система',
    dailyNorm: '15 мг для взрослых',
    bestTimeToTake: 'Утром во время еды',
    form: 'Капсулы',
  ),
  Vitamin(
    id: null,
    name: 'Витамин A',
    abbreviation: 'A',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFF00838F, // тёмно-бирюзовый для Витамина A
    period: 'утро',
    mealRelation: 'во время еды',
    compatibleWith: ['Витамин E', 'Цинк'],
    incompatibleWith: ['Витамин D'],
    description: 'Жирорастворимый витамин, важный для зрения, роста и иммунитета.',
    benefits: 'Поддерживает хорошее зрение, здоровую кожу, иммунитет, рост и развитие.',
    organs: 'Глаза, кожа, иммунная система',
    dailyNorm: '700-900 мкг RAE для взрослых',
    bestTimeToTake: 'Утром во время еды',
    form: 'Капсулы',
  ),
  Vitamin(
    id: null,
    name: 'Витамин B1',
    abbreviation: 'B1',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFFB388FF,
    period: 'утро',
    mealRelation: 'после еды',
    compatibleWith: ['B2', 'B3', 'B5', 'B6', 'B9', 'B12', 'Витамин C', 'Витамин E'],
    incompatibleWith: ['Витамин B12'],
    description: 'Тиамин - водорастворимый витамин, важный для энергетического обмена и нервной системы.',
    benefits: 'Поддерживает энергетический обмен, здоровье нервной системы и работу сердца.',
    organs: 'Нервная система, сердце',
    dailyNorm: '1.1-1.2 мг для взрослых',
    bestTimeToTake: 'Утром после еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Витамин B2',
    abbreviation: 'B2',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFF8C9EFF,
    period: 'утро',
    mealRelation: 'после еды',
    compatibleWith: ['B1', 'B3', 'B5', 'B6', 'B9', 'B12', 'Витамин C', 'Витамин E', 'Цинк', 'Железо'],
    incompatibleWith: [],
    description: 'Рибофлавин - водорастворимый витамин, необходимый для энергетического обмена и клеточного роста.',
    benefits: 'Участвует в производстве энергии, росте клеток, поддерживает здоровье кожи и глаз.',
    organs: 'Кожа, глаза',
    dailyNorm: '1.1-1.3 мг для взрослых',
    bestTimeToTake: 'Утром после еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Витамин B3',
    abbreviation: 'B3',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFF80CBC4,
    period: 'утро',
    mealRelation: 'после еды',
    compatibleWith: ['B1', 'B2', 'B5', 'B6', 'B9', 'B12', 'Витамин C', 'Витамин E'],
    incompatibleWith: [],
    description: 'Ниацин - водорастворимый витамин, важный для энергетического обмена и здоровья кожи.',
    benefits: 'Участвует в производстве энергии, поддерживает здоровье кожи, нервной и пищеварительной систем.',
    organs: 'Кожа, нервная система, пищеварительная система',
    dailyNorm: '14-16 мг NE для взрослых',
    bestTimeToTake: 'Утром после еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Витамин B5',
    abbreviation: 'B5',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFFFFAB91,
    period: 'утро',
    mealRelation: 'после еды',
    compatibleWith: ['B1', 'B2', 'B3', 'B6', 'B9', 'B12', 'Витамин C', 'Витамин E'],
    incompatibleWith: [],
    description: 'Пантотеновая кислота - водорастворимый витамин, участвующий в синтезе кофермента A.',
    benefits: 'Участвует в энергетическом обмене, синтезе гормонов и нейротрансмиттеров.',
    organs: 'Надпочечники, нервная система',
    dailyNorm: '5 мг для взрослых',
    bestTimeToTake: 'Утром после еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Витамин B6',
    abbreviation: 'B6',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFFFFCC80,
    period: 'утро',
    mealRelation: 'после еды',
    compatibleWith: ['B1', 'B2', 'B3', 'B5', 'B9', 'B12', 'Витамин C', 'Магний', 'Цинк'],
    incompatibleWith: [],
    description: 'Пиридоксин - водорастворимый витамин, важный для метаболизма белков и работы нервной системы.',
    benefits: 'Участвует в метаболизме аминокислот, работе нервной системы, производстве нейротрансмиттеров.',
    organs: 'Нервная система',
    dailyNorm: '1.3-1.7 мг для взрослых',
    bestTimeToTake: 'Утром после еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Витамин B7 (биотин)',
    abbreviation: 'B7',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFF689F38, // насыщенный зелёный для Биотина
    period: 'утро',
    mealRelation: 'во время еды',
    compatibleWith: [],
    incompatibleWith: [],
    description: 'Биотин - водорастворимый витамин, важный для метаболизма жиров, углеводов и белков.',
    benefits: 'Поддерживает здоровье волос, кожи и ногтей, участвует в метаболизме энергии.',
    organs: 'Волосы, кожа, ногти',
    dailyNorm: '30 мкг для взрослых',
    bestTimeToTake: 'Утром во время еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Фолиевая кислота',
    abbreviation: 'B9',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFFAED581,
    period: 'утро',
    mealRelation: 'после еды',
    compatibleWith: ['B6', 'B12', 'Витамин C', 'Железо'],
    incompatibleWith: ['Цинк'],
    description: 'Фолиевая кислота - водорастворимый витамин, необходимый для синтеза ДНК и РНК.',
    benefits: 'Важен для роста и развития клеток, особенно во время беременности.',
    organs: 'Кровь, нервная система',
    dailyNorm: '400 мкг DFE для взрослых',
    bestTimeToTake: 'Утром после еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Витамин K',
    abbreviation: 'K',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFF81C784,
    period: 'утро',
    mealRelation: 'во время еды',
    compatibleWith: ['Кальций', 'Витамин D'],
    incompatibleWith: ['Витамин E', 'Антикоагулянты (Варфарин)'],
    description: 'Жирорастворимый витамин, необходимый для свертывания крови и здоровья костей.',
    benefits: 'Участвует в свертывании крови и поддержании здоровья костей.',
    organs: 'Кровь, кости',
    dailyNorm: '90-120 мкг для взрослых',
    bestTimeToTake: 'Утром во время еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Витамин PP',
    abbreviation: 'PP',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFFFFD54F,
    period: 'утро',
    mealRelation: 'после еды',
    compatibleWith: ['B1', 'B2', 'B5', 'B6', 'B9', 'B12', 'Витамин C', 'Витамин E'],
    incompatibleWith: [],
    description: 'Ниацин - водорастворимый витамин (см. Витамин B3). Используется также для снижения холестерина.',
    benefits: 'Снижает уровень холестерина, поддерживает здоровье кожи и нервной системы.',
    organs: 'Сердце, кожа, нервная система',
    dailyNorm: '14-16 мг NE для взрослых',
    bestTimeToTake: 'Утром после еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Селен',
    abbreviation: 'Se',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFF90A4AE,
    period: 'утро',
    mealRelation: 'после еды',
    compatibleWith: ['Витамин E', 'Витамин C'],
    incompatibleWith: ['Цинк'],
    description: 'Микроэлемент, важный для щитовидной железы и иммунной системы.',
    benefits: 'Поддерживает функцию щитовидной железы, иммунитет, является антиоксидантом.',
    organs: 'Щитовидная железа, иммунная система',
    dailyNorm: '55 мкг для взрослых',
    bestTimeToTake: 'Утром после еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Йод',
    abbreviation: 'I',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFFa7532a,
    period: 'утро',
    mealRelation: 'во время еды',
    compatibleWith: [],
    incompatibleWith: [],
    description: 'Микроэлемент, необходимый для синтеза гормонов щитовидной железы.',
    benefits: 'Поддерживает функцию щитовидной железы, метаболизм.',
    organs: 'Щитовидная железа',
    dailyNorm: '150 мкг для взрослых',
    bestTimeToTake: 'Утром во время еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Калий',
    abbreviation: 'K',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFFFFA000, // насыщенный янтарный для Калия
    period: 'утро',
    mealRelation: 'во время еды',
    compatibleWith: ['Магний'],
    incompatibleWith: [],
    description: 'Минерал, важный для работы сердца, мышц и нервной системы.',
    benefits: 'Регулирует кровяное давление, поддерживает работу мышц и нервов.',
    organs: 'Сердце, мышцы, нервная система',
    dailyNorm: '2600-3400 мг для взрослых',
    bestTimeToTake: 'Утром или днем во время еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Натрий',
    abbreviation: 'Na',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFFCFD8DC,
    period: 'утро',
    mealRelation: 'во время еды',
    compatibleWith: [],
    incompatibleWith: [],
    description: 'Минерал, важный для баланса жидкости и работы нервной системы.',
    benefits: 'Регулирует баланс жидкости, участвует в работе нервной системы и мышц.',
    organs: 'Почки, нервная система, мышцы',
    dailyNorm: '1500 мг для взрослых',
    bestTimeToTake: 'В любое время с едой',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Фосфор',
    abbreviation: 'P',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFFB0BEC5,
    period: 'утро',
    mealRelation: 'во время еды',
    compatibleWith: ['Кальций', 'Витамин D'],
    incompatibleWith: ['Магний', 'Алюминий'],
    description: 'Минерал, важный для костей, зубов и энергетического обмена.',
    benefits: 'Необходим для здоровья костей и зубов, участвует в производстве энергии.',
    organs: 'Кости, зубы',
    dailyNorm: '700 мг для взрослых',
    bestTimeToTake: 'Утром или днем во время еды',
    form: 'Таблетки',
  ),
  Vitamin(
    id: null,
    name: 'Медь',
    abbreviation: 'Cu',
    dosage: 1,
    startDate: DateTime.now(),
    endDate: DateTime.now(),
    unit: 'таблетка',
    color: 0xFFBCAAA4,
    period: 'утро',
    mealRelation: 'после еды',
    compatibleWith: ['Железо', 'Витамин C'],
    incompatibleWith: ['Цинк', 'Витамин B12'],
    description: 'Микроэлемент, важный для образования красных кровяных телец и соединительной ткани.',
    benefits: 'Необходима для усвоения железа, здоровья соединительной ткани, работы мозга.',
    organs: 'Кровь, соединительная ткань, мозг',
    dailyNorm: '900 мкг для взрослых',
    bestTimeToTake: 'Утром или днем после еды',
    form: 'Таблетки',
  ),
]; 